/**
 * `blitzstrahl check` (PLAN §7): everything that can be found out about a
 * deck before you're standing in front of a room. Parse problems, missing
 * files, render blocks that would fail, step gaps, classes that do nothing,
 * slides that overflow, and embedded sites that refuse to be framed. Every
 * finding points at `deck.md:line:col`.
 */
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, relative, resolve } from 'node:path'
import type { Deck, Diagnostic, HastNode, SourceSpan } from '@blitzstrahl/core'
import { runtimeCss } from '@blitzstrahl/runtime/css'
import { asFeatureCollection, dataOptions, isUrl, markersFromText, tileSource, type MapSpec } from '@blitzstrahl/renderers/specs'
import { build } from './build.js'
import { allCss } from './extend.js'
import { fontDiagnostics } from './fonts.js'
import { deckStyles, loadDeck, type LoadedDeck } from './load.js'
import { checkBuiltOverflow } from './overflow.js'

export interface CheckOptions {
  /** Skip everything that needs the network (the embed probes). */
  offline?: boolean
  /** Skip measuring overflow (it needs a browser). */
  overflow?: boolean
  /** Per-request timeout for embed probes, in ms. */
  timeout?: number
  /** The deck's markdown, instead of reading the file (`--stdin`). */
  source?: string
}

export interface CheckResult {
  diagnostics: Diagnostic[]
  /** Parts of the check that couldn't run, and why. */
  skipped: string[]
}

export async function check(deckPath: string, options: CheckOptions = {}): Promise<CheckResult> {
  const abs = resolve(deckPath)
  const loaded = await loadDeck(abs, relative(process.cwd(), abs) || abs, options.source !== undefined ? { source: options.source } : {})
  const { deck } = loaded
  const { theme } = loaded.extras
  const found: Diagnostic[] = [...loaded.diagnostics]
  const skipped: string[] = []
  const add = (severity: Diagnostic['severity'], code: string, message: string, span: SourceSpan) =>
    found.push({ severity, code, message, file: deck.source, span })

  // Render blocks are checked by loadDeck, for build and dev too.

  for (const slide of deck.slides) {
    for (const s of stepGaps(slide.content, slide.steps)) {
      add('warning', 'step/gap', `slide \`${slide.id}\`: step ${s} changes nothing, so that press does nothing`, firstLine(slide.span, loaded.source))
    }
  }

  found.push(...unusedClasses(deck, loaded.source, allCss(loaded.extras) + runtimeCss + loaded.css))

  found.push(...fontDiagnostics(deck, loaded.extras.fonts, theme.tokens, deck.meta.theme, (i) => firstLine(deck.slides[i]!.span, loaded.source)))

  found.push(...mapNotes(deck), ...altNotes(deck))
  if (!options.offline) found.push(...(await probeEmbeds(deck, options.timeout ?? 8000)), ...(await probeGeometry(deck, options.timeout ?? 8000)))
  else {
    if (deck.slides.some((s) => s.blocks.some((b) => b.renderer === 'embed'))) skipped.push('embedded sites (--offline)')
    if (geometryUrls(deck).size) skipped.push('map data from URLs (--offline)')
  }

  if (options.overflow !== false) {
    const over = await measure(loaded)
    found.push(...over.diagnostics)
    if (over.skipped) skipped.push(`overflow: ${over.skipped}`)
  }

  found.sort((a, b) => a.span.start.line - b.span.start.line || a.span.start.column - b.span.start.column)
  return { diagnostics: dedupe(found), skipped }
}

function point(line: number, column = 1): SourceSpan {
  return { start: { line, column }, end: { line, column } }
}

/** A slide's first non-blank line, where slide-level findings point. */
function firstLine(span: SourceSpan, source: string): SourceSpan {
  const lines = source.replace(/\r\n?/g, '\n').split('\n')
  let line = span.start.line
  while (line < span.end.line && !lines[line - 1]?.trim()) line++
  return point(line)
}

function dedupe(list: Diagnostic[]): Diagnostic[] {
  const seen = new Set<string>()
  return list.filter((d) => {
    const key = `${d.span.start.line}:${d.span.start.column}:${d.code}:${d.message}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}

/** Elements with build steps, from the IR's hast. */
function* stepped(nodes: HastNode[]): Generator<Record<string, unknown>> {
  for (const n of nodes) {
    if (n.type !== 'element') continue
    if (n.properties.dataBlitzStepIn !== undefined) yield n.properties
    yield* stepped(n.children)
  }
}

/**
 * Steps 1…N at which nothing enters or leaves, and no emphasis turns on or
 * off (syntax.md §6.2: gaps are allowed, and `check` warns about them).
 */
export function stepGaps(content: HastNode[], steps: number): number[] {
  const busy = new Set<number>()
  for (const p of stepped(content)) {
    busy.add(Number(p.dataBlitzStepIn))
    if (p.dataBlitzStepOut !== undefined) busy.add(Number(p.dataBlitzStepOut) + 1)
  }
  return Array.from({ length: steps }, (_, i) => i + 1).filter((s) => !busy.has(s))
}

/**
 * Classes that mean something without any CSS: generated by blitzstrahl or
 * markdown itself, or given meaning by blitzstrahl (`.sortable`, `.column`).
 */
const OWN = /^(blitz-|language-)|^(contains-task-list|task-list-item|footnotes|sr-only|data-footnote-backref|footnote-label|shiki|line|sortable|column)$/

/** Effect names (syntax.md §6.3), for "did you mean". */
const EFFECT_NAMES = [
  'fade', 'fade-up', 'fade-down', 'fade-left', 'fade-right', 'pop', 'zoom', 'blur-in',
  'slide-in-up', 'slide-in-down', 'slide-in-left', 'slide-in-right', 'draw', 'count-up',
  'typewriter', 'highlight', 'strike', 'dim-others',
]

function classesIn(nodes: HastNode[], out = new Set<string>()): Set<string> {
  for (const n of nodes) {
    if (n.type !== 'element') continue
    const c = n.properties.className
    if (Array.isArray(c)) for (const x of c) out.add(String(x))
    classesIn(n.children, out)
  }
  return out
}

/**
 * Classes on slide content that neither the theme nor the deck's own
 * `<style>` mentions: probably a typo, or an effect name that isn't one
 * (syntax.md §6.3). Close to an effect name → warning; otherwise info.
 */
export function unusedClasses(deck: Deck, source: string, css: string): Diagnostic[] {
  const styles = deckStyles(source)
  const styled = new Set([...(css + '\n' + styles).matchAll(/\.(-?[_a-zA-Z][\w-]*)/g)].map((m) => m[1]!))
  const used = new Set<string>()
  for (const s of deck.slides) classesIn(s.content, used)
  const lines = source.replace(/\r\n?/g, '\n').split('\n')
  const out: Diagnostic[] = []
  for (const cls of [...used].sort()) {
    if (OWN.test(cls) || styled.has(cls)) continue
    const esc = cls.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    // Only classes written as `.name` in an attribute block. A container's
    // name (`::: stat`) is grouping, and often meant to carry no style.
    const re = new RegExp(`\\{[^}]*\\.${esc}(?![\\w-])`)
    const k = lines.findIndex((l) => re.test(l))
    if (k < 0) continue
    const dot = new RegExp(`\\.${esc}(?![\\w-])`)
    const column = lines[k]!.search(dot) + 1
    const near = EFFECT_NAMES.find((e) => close(cls, e))
    out.push({
      severity: near ? 'warning' : 'info',
      code: near ? 'class/near-effect' : 'class/unstyled',
      message: near
        ? `\`.${cls}\` isn't an effect or styled by the theme: did you mean \`.${near}\`?`
        : `\`.${cls}\` isn't styled by the theme or the deck, so it does nothing`,
      file: deck.source,
      span: point(k + 1, column),
    })
  }
  return out
}

function close(a: string, b: string): boolean {
  if (a.startsWith(b + '-') || b.startsWith(a + '-')) return true
  return distance(a, b) <= Math.min(2, Math.floor(b.length / 3))
}

function distance(a: string, b: string): number {
  const d = Array.from({ length: b.length + 1 }, (_, j) => j)
  for (let i = 1; i <= a.length; i++) {
    let prev = d[0]!
    d[0] = i
    for (let j = 1; j <= b.length; j++) {
      const t = d[j]!
      d[j] = Math.min(d[j]! + 1, d[j - 1]! + 1, prev + (a[i - 1] === b[j - 1] ? 0 : 1))
      prev = t
    }
  }
  return d[b.length]!
}

/**
 * Ask each embedded site whether it may be framed (CLAUDE.md: catch it in
 * `check`, don't engineer around it): `X-Frame-Options`, and CSP
 * `frame-ancestors`. The deck's own origin isn't known here (it may be a
 * file, or any host), so anything short of "anyone may frame this" is a
 * warning.
 */
/** Maps' specs, where they're valid enough to read. */
function maps(deck: Deck): Array<{ spec: MapSpec; span: SourceSpan }> {
  return deck.slides
    .flatMap((s) => s.blocks)
    .filter((b) => b.renderer === 'map' && b.spec && typeof b.spec === 'object' && !Array.isArray(b.spec))
    .map((b) => ({ spec: b.spec as MapSpec, span: b.span }))
}

/**
 * Maps have no street map unless the deck names one (map.md): say so, once
 * per map without `tiles`, and ask for a credit where a custom provider
 * has none.
 */
export function mapNotes(deck: Deck): Diagnostic[] {
  const out: Diagnostic[] = []
  for (const { spec, span } of maps(deck)) {
    if (spec.tiles === undefined) {
      out.push({ severity: 'info', code: 'map/no-tiles', message: 'this map has no street map under it: set `tiles` to a provider (`tiles: osm`, or a URL template), or `tiles: none` to say that\'s intended', file: deck.source, span })
    } else if (typeof spec.tiles === 'string' && !tileSource(spec)?.attribution) {
      out.push({ severity: 'warning', code: 'map/no-attribution', message: 'tile providers require credit: add `attribution` (it shows in the corner of the map)', file: deck.source, span })
    }
  }
  return out
}

/** Blocks a screen reader sees as one picture, which `alt=` should describe (syntax.md §8.2). */
const DESCRIBED = new Set(['chart', 'map', 'mermaid'])

/** A chart, map or diagram without `alt=`: a note, never a warning (a chart describes itself from its data). */
export function altNotes(deck: Deck): Diagnostic[] {
  const named = new Set<string>()
  const walk = (nodes: HastNode[]) => {
    for (const n of nodes) {
      if (n.type !== 'element') continue
      if (typeof n.properties.dataBlitzBlock === 'string' && n.properties.ariaLabel) named.add(n.properties.dataBlitzBlock)
      walk(n.children as HastNode[])
    }
  }
  const out: Diagnostic[] = []
  for (const slide of deck.slides) {
    walk(slide.content)
    for (const b of slide.blocks) {
      if (!DESCRIBED.has(b.renderer) || named.has(b.id)) continue
      out.push({ severity: 'info', code: 'block/no-alt', message: `this ${b.renderer} has no \`alt=\`: say what it shows, for screen readers (syntax.md §8.2)`, file: deck.source, span: b.span })
    }
  }
  return out
}

/** `markers` and `regions` URLs, with where each is first used. */
function geometryUrls(deck: Deck): Map<string, { span: SourceSpan; key: 'markers' | 'regions'; spec: MapSpec }> {
  const out = new Map<string, { span: SourceSpan; key: 'markers' | 'regions'; spec: MapSpec }>()
  for (const { spec, span } of maps(deck)) {
    for (const key of ['markers', 'regions'] as const) {
      const v = spec[key]
      if (typeof v === 'string' && isUrl(v) && !out.has(v)) out.set(v, { span, key, spec })
    }
  }
  return out
}

/**
 * Fetch each map's `markers` / `regions` URL the way the page will: it must
 * answer, hold what the map expects, and let other pages read it (CORS),
 * or the browser refuses it however well the server answers.
 */
export async function probeGeometry(deck: Deck, timeout: number): Promise<Diagnostic[]> {
  const out: Diagnostic[] = []
  await Promise.all(
    [...geometryUrls(deck)].map(async ([url, { span, key, spec }]) => {
      const warn = (code: string, message: string) => out.push({ severity: 'warning', code, message, file: deck.source, span })
      let res: Response
      let text: string
      try {
        res = await fetch(url, { redirect: 'follow', signal: AbortSignal.timeout(timeout) })
        text = await res.text()
      } catch (err) {
        const why = err instanceof Error && err.name === 'TimeoutError' ? `no answer in ${timeout / 1000}s` : err instanceof Error ? (err.cause as Error | undefined)?.message ?? err.message : String(err)
        warn('map/unreachable', `couldn't reach ${url} (${why}); the map will be missing its \`${key}\` if it can't during the talk`)
        return
      }
      if (res.status >= 400) {
        warn('map/status', `${url} answers ${res.status} ${res.statusText}`.trim())
        return
      }
      const cors = res.headers.get('access-control-allow-origin')?.trim()
      if (cors !== '*') {
        warn('map/cors', cors ? `${url} only lets ${cors} read it (CORS), so the deck's page can't` : `${url} doesn't let other pages read it (no Access-Control-Allow-Origin header), so the browser will refuse it`)
      }
      try {
        if (key === 'markers') markersFromText(url, text, spec.label, spec.size, dataOptions(spec, deck.meta))
        else asFeatureCollection(JSON.parse(text), '`regions`')
      } catch (err) {
        out.push({ severity: 'error', code: 'map/data', message: `\`${key}\` from ${url}: ${(err as Error).message}`, file: deck.source, span })
      }
    }),
  )
  return out
}

export async function probeEmbeds(deck: Deck, timeout: number): Promise<Diagnostic[]> {
  const blocks = deck.slides.flatMap((s) => s.blocks).filter((b) => b.renderer === 'embed')
  const bySrc = new Map<string, SourceSpan>()
  for (const b of blocks) {
    const spec = b.spec as { src?: unknown } | string | null
    const src = typeof spec === 'string' ? spec : spec?.src
    if (typeof src === 'string' && /^https?:\/\//i.test(src) && !bySrc.has(src)) bySrc.set(src, b.span)
  }
  const out: Diagnostic[] = []
  await Promise.all(
    [...bySrc].map(async ([src, span]) => {
      const warn = (code: string, message: string) => out.push({ severity: 'warning', code, message, file: deck.source, span })
      let res: Response
      try {
        res = await fetch(src, { method: 'HEAD', redirect: 'follow', signal: AbortSignal.timeout(timeout) })
        if (res.status === 405 || res.status === 501) res = await fetch(src, { redirect: 'follow', signal: AbortSignal.timeout(timeout) })
      } catch (err) {
        const why = err instanceof Error && err.name === 'TimeoutError' ? `no answer in ${timeout / 1000}s` : err instanceof Error ? (err.cause as Error | undefined)?.message ?? err.message : String(err)
        warn('embed/unreachable', `couldn't reach ${src} (${why}); it may not load during the talk either`)
        return
      }
      void res.body?.cancel()
      if (res.status >= 400) {
        warn('embed/status', `${src} answers ${res.status} ${res.statusText}`.trim())
        return
      }
      const xfo = res.headers.get('x-frame-options')?.trim().toUpperCase()
      if (xfo && /DENY|SAMEORIGIN|ALLOW-FROM/.test(xfo)) {
        warn('embed/refused', `${src} refuses to be shown in a frame (X-Frame-Options: ${xfo}); use a screenshot instead`)
        return
      }
      const ancestors = frameAncestors(res.headers.get('content-security-policy'))
      if (ancestors !== undefined && !ancestors.includes('*')) {
        const who = ancestors.length === 0 || ancestors.includes("'none'") ? 'any page' : `pages other than ${ancestors.join(' ')}`
        warn('embed/refused', `${src} refuses to be shown in a frame by ${who} (CSP frame-ancestors); use a screenshot instead`)
      }
    }),
  )
  return out
}

/** Sources of CSP `frame-ancestors`, or undefined if not restricted. */
function frameAncestors(csp: string | null): string[] | undefined {
  if (!csp) return undefined
  for (const policy of csp.split(',')) {
    for (const directive of policy.split(';')) {
      const [name, ...values] = directive.trim().split(/\s+/)
      if (name?.toLowerCase() === 'frame-ancestors') return values
    }
  }
  return undefined
}

/** Build to a temporary folder and measure it (the same check `build` runs). */
async function measure(loaded: LoadedDeck): Promise<{ diagnostics: Diagnostic[]; skipped?: string }> {
  const tmp = await mkdtemp(join(tmpdir(), 'blitz-check-'))
  try {
    const built = await build(loaded.path, { outDir: tmp, quiet: true, report: false, force: true, overflowCheck: false, loaded })
    if (!built.index) return { diagnostics: [], skipped: "the deck couldn't be built" }
    return await checkBuiltOverflow(tmp, loaded.deck, loaded.source)
  } finally {
    await rm(tmp, { recursive: true, force: true })
  }
}
